kind: BuildConfig
apiVersion: v1
metadata:
  name: hello
  labels:
    app: hello
spec:
  source:
    type: Git
    git:
      uri: https://github.com/etoews/hello-kubernetes.git
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: hello:latest
